AWSTemplateFormatVersion: "2010-09-09"
Description: NAT Instance with ImportValue for SG and Subnets

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair for NAT Instance SSH

  NATInstanceAMI:
    Type: AWS::EC2::Image::Id
    Default: ami-0015c0130d6cc5da7
    Description: NAT Instance AMI

Resources:

  NATSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: NAT Instance Security Group
      VpcId: !ImportValue VpcId
      Tags:
        - Key: Name
          Value: "lks-sg-nat"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 20.2.2.0/24
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 20.2.3.0/24
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 20.2.2.0/24
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 20.2.3.0/24

  NATInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref NATInstanceAMI
      KeyName: !Ref KeyPairName
      SourceDestCheck: false
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref NATSecurityGroup
          SubnetId: !ImportValue PublicSubnet1aID
      Tags:
        - Key: Name
          Value: NAT-Instance

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      InstanceId: !Ref NATInstance

Outputs:
  NATInstanceId:
    Value: !Ref NATInstance
  NATIP:
    Value: !Ref ElasticIP
