AWSTemplateFormatVersion: 2010-09-09
Description: Public S3 for Images

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lks-kabbanyumas-fadhil-25

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"